# Generated by Django 5.1.7 on 2025-03-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_contact',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
