# Generated by Django 5.1.7 on 2025-03-25 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_tag'),
        ('venues', '0002_alter_venue_venue_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_time', models.DateTimeField()),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.room')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.show')),
            ],
        ),
    ]
