# Generated by Django 5.1.7 on 2025-03-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='seat_price',
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.FloatField(default=10.0),
            preserve_default=False,
        ),
    ]
