# Generated by Django 5.1.7 on 2025-03-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_remove_seat_seat_price_event_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='seat_layout',
        ),
        migrations.AddField(
            model_name='seat',
            name='location_x',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='location_y',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
