# Generated by Django 5.1.7 on 2025-03-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_remove_room_seat_layout_seat_location_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_columns',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_rows',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
