# Generated by Django 5.1.7 on 2025-03-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_room_room_columns_room_room_rows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='location_x',
            new_name='location_column',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='location_y',
            new_name='location_row',
        ),
    ]
