# Generated by Django 5.1.7 on 2025-03-29 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
        ('venues', '0007_rename_location_x_seat_location_column_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedSeat',
            fields=[
                ('booking_id', models.UUIDField(primary_key=True, serialize=False)),
                ('booked_status', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.event')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.order')),
                ('seat_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.seat')),
            ],
        ),
    ]
