# Generated by Django 5.1.7 on 2025-03-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_bookedseat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedseat',
            name='booked_status',
            field=models.BooleanField(default=True),
        ),
    ]
