# Generated by Django 5.1.7 on 2025-04-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_alter_bookedseat_booked_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='location_column',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='seat',
            name='location_row',
            field=models.IntegerField(default=1),
        ),
    ]
