# Generated by Django 5.1.7 on 2025-04-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0010_alter_seat_location_column_alter_seat_location_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_columns',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_rows',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='seat',
            name='location_column',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='location_row',
            field=models.IntegerField(),
        ),
    ]
