# Generated by Django 5.1.7 on 2025-04-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0012_alter_room_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
