# Generated by Django 5.1.7 on 2025-04-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0013_event_public_venue_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_columns',
            field=models.IntegerField(default=19),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_rows',
            field=models.IntegerField(default=8),
        ),
    ]
