# Generated by Django 5.1.7 on 2025-04-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0014_alter_room_room_columns_alter_room_room_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='working_hours',
            field=models.CharField(help_text='"HH:MM-HH:MM"(opening-closing)', max_length=10),
        ),
    ]
