# Generated by Django 5.1.7 on 2025-04-28 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0015_alter_venue_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_columns',
            field=models.IntegerField(default=19, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_rows',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='venue',
            name='working_hours',
            field=models.CharField(help_text='"HH:MM-HH:MM"(opening-closing)', max_length=11),
        ),
    ]
