# Generated by Django 5.2 on 2025-04-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0016_alter_room_room_columns_alter_room_room_rows_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['venue_name']},
        ),
    ]
