# Generated by Django 5.1.7 on 2025-03-29 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('date_ordered', models.DateField(auto_now_add=True)),
                ('billing_name', models.CharField(max_length=250)),
                ('billing_address', models.CharField(max_length=250)),
                ('billing_city', models.CharField(max_length=250)),
                ('billing_postcode', models.CharField(max_length=10)),
                ('billing_country', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
