# Generated by Django 5.2 on 2025-04-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('date_ordered',)},
        ),
    ]
