# Generated by Django 5.1.7 on 2025-03-21 21:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('show_id', models.SlugField(primary_key=True, serialize=False)),
                ('show_name', models.CharField(max_length=200)),
                ('show_type', models.CharField(max_length=30)),
                ('show_duration', models.IntegerField()),
                ('show_description', models.TextField()),
                ('show_agerating', models.CharField(max_length=20)),
                ('show_release_date', models.DateField()),
                ('show_language', models.CharField(max_length=20)),
                ('show_banner', models.ImageField(upload_to='')),
                ('public', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ShowMember',
            fields=[
                ('show_member_id', models.SlugField(primary_key=True, serialize=False)),
                ('show_member_type', models.CharField(max_length=20)),
                ('show_member_name', models.CharField(max_length=50)),
                ('show_member_banner', models.ImageField(upload_to='')),
                ('public', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating_value', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.show')),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('following_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.show')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(primary_key=True, serialize=False)),
                ('comment_content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.show')),
            ],
        ),
        migrations.CreateModel(
            name='MemberJunction',
            fields=[
                ('member_junction_id', models.AutoField(primary_key=True, serialize=False)),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.show')),
                ('show_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.showmember')),
            ],
        ),
    ]
