# Generated by Django 5.1.7 on 2025-04-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='showmember',
            name='shows',
            field=models.ManyToManyField(to='shows.show'),
        ),
        migrations.DeleteModel(
            name='MemberJunction',
        ),
    ]
