# Generated by Django 5.1.7 on 2025-04-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_alter_show_show_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='public',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_banner',
            field=models.ImageField(blank=True, upload_to='shows/'),
        ),
    ]
