# Generated by Django 5.1.7 on 2025-04-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_alter_show_show_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_release_date',
            field=models.DateField(help_text='"YYYY-MM-DD"'),
        ),
    ]
